### ISSUE TITLE
TypeError: FluxAttentionControl.xformers_attention() got an unexpected keyword argument 'mask'

### ISSUE THREAD

**Issue by EnragedAntelope** [gseth/ControlAltAI-Nodes#13]
Not sure if an issue with xformers (I have v0.0.28.post3) but I am consistently running into this error immediately after the Flux Attention node before the sampler. 

```
!!! Exception during processing !!! FluxAttentionControl.xformers_attention() got an unexpected keyword argument 'mask'
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ControlAltAI-Nodes\flux_sampler_node.py", line 52, in sample
    samples = sampler.sample(noise, positive, negative, cfg=1.0, latent_image=latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 117, in KSampler_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\utils.py", line 51, in KSampler_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 1013, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 135, in sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 911, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 897, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 866, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 850, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 100, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 707, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\k_diffusion\sampling.py", line 1098, in sample_deis
    denoised = model(x_cur, t_cur * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 379, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 832, in __call__
    return self.predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 835, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 175, in sampling_function
    out = orig_fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 359, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 195, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\samplers.py", line 308, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\model_base.py", line 129, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\model_base.py", line 158, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\ldm\flux\model.py", line 204, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control, transformer_options, attn_mask=kwargs.get("attention_mask", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\ldm\flux\model.py", line 143, in forward_orig
    img, txt = block(img=img,
               ^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\comfy\ldm\flux\layers.py", line 174, in forward
    attn = attention(torch.cat((txt_q, img_q), dim=2),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FluxAttentionControl.xformers_attention() got an unexpected keyword argument 'mask'
```

**Comment by gseth** [comment]
Update: 20 Dec 2024: Due to the addition of attention mask in Flux and change of environment here: https://github.com/comfyanonymous/ComfyUI/pull/5942, Flux Region Spatial Control code is now redundant and will only work with older versions of comfy UI. This will not work in ComfyUI v0.3.8-4-g3cacd3f, ComfyUI_frontend v1.5.19 and above.

If you want I can link a downloaded instance of Comfy which works with this. They have broken everything, it now has to be coded from scratch and the results won't be the same. I am not sure If I am going to pursue fixing it, as you can understand it took 1.5 months to proper stabilize this as per currently environment, and it few days for them to change the entire environment to accommodate Flux Redux.

**Comment by f4cyw** [comment]
I have same issue and I'm really upset :( Hopefully I would like to use this workflow....

**Comment by gseth** [comment]
@EnragedAntelope Thanks! I laid out a plan for Flux Attention Mask nodes In case they decide not to revert back. It will take a month or so, but we will have a new set of nodes with region control using their new attention mask. Regional Lora, ControlNet will be supported on day 1 for that.

@f4cyw 

here is the zip instance of comfy from my computer, I have deleted everything and kept only 4 custom nodes which requires this:

https://drive.google.com/file/d/1MvvJ3rXGF6vbtIeKM8vX9ZoZKWgcrYGH/view

You can download this, put the required models. and run it separately. The workflow will work as intended.

**Comment by gseth** [comment]
@EnragedAntelope @f4cyw 

Update ControlAltAI nodes, I have fixed it as per instructions given here: https://github.com/comfyanonymous/ComfyUI/pull/5942#issuecomment-2557667589

Everything is working as intended.

**Comment by EnragedAntelope** [comment]
Fantastic!! I’ll update asap and give it another try. Thanks for the great follow up.

**Comment by gseth** [comment]
> Fantastic!! I’ll update asap and give it another try. Thanks for the great follow up.

I am still planning to make the Flux Attention Mask Pipeline......lol Let me know if it works at your end or not. So I can get some peace of mind here. Thanks.

**Comment by EnragedAntelope** [comment]
I am not totally sure as I only just started using these nodes. I no longer get the error so that part is good, and the workflow completes. However it is very rare that I get all 3 of my test subjects (dog cat bird) in one scene when I've just repeatedly tried. Might be strength etc. related but I've been trying quite a few variations. This is the closest I've come out of ~20, the bird is a little outside of the target box:
![image](https://github.com/user-attachments/assets/236357cd-175d-4cff-95d3-27a668762b4f)

Making you aware of this in case the comfy change was negatively impactful, but it could also be that I am doing something wrong.

**Comment by EnragedAntelope** [comment]
Continued testing looks generally good for me (I guess things don't totally stay in the boxes) so I do think the update was a success. Thank you again!

![image](https://github.com/user-attachments/assets/bd9b5543-bd69-4592-b1f8-3237dd8ac198)

**Comment by gseth** [comment]
> I am not totally sure as I only just started using these nodes. I no longer get the error so that part is good, and the workflow completes. However it is very rare that I get all 3 of my test subjects (dog cat bird) in one scene when I've just repeatedly tried. Might be strength etc. related but I've been trying quite a few variations. This is the closest I've come out of ~20, the bird is a little outside of the target box: ![image](https://private-user-images.githubusercontent.com/176548309/397905549-236357cd-175d-4cff-95d3-27a668762b4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTkyMzIsIm5iZiI6MTczNDc1ODkzMiwicGF0aCI6Ii8xNzY1NDgzMDkvMzk3OTA1NTQ5LTIzNjM1N2NkLTE3NWQtNGNmZi05NWQzLTI3YTY2ODc2MmI0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQwNTI4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjNmOTFhMTAxOGU1YzVkNWY3ZjIxODkxZGI5MTNhOWNhZWFmNzYwYjMxZWM1YjI2Yjc2NDgxYTEyNDZkZmI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6pmcWJuS-CMVpagVb47l4f2DV6cvjooT9OUcusYNzss)
> 
> Making you aware of this in case the comfy change was negatively impactful, but it could also be that I am doing something wrong.

Hi, This is normal. Don't expect it to be within the box, I will be in that area but outside the box. Because the AI needs to make sense out of it. I have explained this in a video. When there are three regions there is a pool effect, the AI sees it as a whole and it has to make the best of all data given in, this includes the canvas size, the region size relative to each other and relative in % to the total canvas size, the prompting, the strengths are relative to each other and to other parts of this complex attention. The feathering the samne relative to each other in combination of everything. 

So I suggest you watch my youtube tutorial, this one a deep learning curve and application beyond positioning subjects: 

https://youtu.be/kNwz6kJRDc0?si=PUAl_zL6nbcd75rv

I explain technically why when things go out of the box, what to do and how to do it and other use cases, some very creative ones.

So here it is working as intended. But they will never stay in the box, so Batman and Superman can never be that height unless you write a kid wearing a Batman and Superman costume. So there is a conflict. Whenever there is a conflict, it tries to rely on base conditioning and its own training to give the most aesthetic rather than deformed output.

If you have any questions, feel free to ask here or via email. But watch the video for the best insight and technical understanding of this.

**Comment by gseth** [comment]
@EnragedAntelope Basically skip half the video and watch it from the Chapter "Understanding regions" that's is why is explain your exact issue and how to over come it.

Here is the link. 

https://youtu.be/kNwz6kJRDc0?si=ljrDLXytGG2txL95&t=1284

**Comment by EnragedAntelope** [comment]
Thank you again!
